### ISSUE TITLE
[Tracking] Generation of testing data

### ISSUE THREAD

**Issue by DennisFGardner** [DennisFGardner/imageCorrelation#4]
For testing of the imageCorrelation program I will need some data to test the code. 

## TODO
- [x] Find some image data to test the code
- [x] Save the image data in a matlab file format
- [x] Write a first version of the imageCorrelation program
- [x] Test the first version of the program with the test data

**Comment by DennisFGardner** [comment]
As a start, I will use a square and move it around sinusoidally.

**Comment by DennisFGardner** [comment]
when testing, what happens when the shapes are small and the shifts are large? I suspect zeros gamma will happen.

**Comment by DennisFGardner** [comment]
I have made some simple test data, sinusoidal motion of a square and did a preliminary test of the code. It seems to be behaving as expected.
